ALTER TABLE tags ADD COLUMN IF NOT EXISTS specificity REAL;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS specificity_llm REAL;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS specificity_embedding REAL;
ALTER TABLE tags ADD COLUMN IF NOT EXISTS specificity_computed_at TIMESTAMPTZ;
