// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assign_issue.sql

package issuesdb

import (
	"context"
)

const assignIssue = `-- name: AssignIssue :exec
UPDATE issues SET assigned_to = $1 WHERE id = $2
`

type AssignIssueParams struct {
	AssignedTo string
	ID         string
}

func (q *Queries) AssignIssue(ctx context.Context, arg AssignIssueParams) error {
	_, err := q.db.ExecContext(ctx, assignIssue, arg.AssignedTo, arg.ID)
	return err
}
