// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: close_issue.sql

package issuesdb

import (
	"context"
)

const closeIssue = `-- name: CloseIssue :exec
UPDATE issues
SET status = 'closed',
    closed_at_unix_nano = $1,
    closed_by = $2
WHERE id = $3
`

type CloseIssueParams struct {
	ClosedAtUnixNano int64
	ClosedBy         string
	ID               string
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) error {
	_, err := q.db.ExecContext(ctx, closeIssue, arg.ClosedAtUnixNano, arg.ClosedBy, arg.ID)
	return err
}
