// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: close_issue.sql

package issuesdb

import (
	"context"
)

const closeIssue = `-- name: CloseIssue :exec
UPDATE issues
SET status = 'closed',
    closed_at_unix_nano = $1,
    closed_by = $2,
    closed_reason = $3,
    closed_reason_note = $4
WHERE id = $5
`

type CloseIssueParams struct {
	ClosedAtUnixNano int64
	ClosedBy         string
	ClosedReason     string
	ClosedReasonNote string
	ID               string
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) error {
	_, err := q.db.ExecContext(ctx, closeIssue,
		arg.ClosedAtUnixNano,
		arg.ClosedBy,
		arg.ClosedReason,
		arg.ClosedReasonNote,
		arg.ID,
	)
	return err
}
