// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_all_issue_links.sql

package issuesdb

import (
	"context"
)

const deleteAllIssueLinks = `-- name: DeleteAllIssueLinks :exec
DELETE FROM issue_links
`

func (q *Queries) DeleteAllIssueLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueLinks)
	return err
}
