// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_all_issue_operations.sql

package issuesdb

import (
	"context"
)

const deleteAllIssueOperations = `-- name: DeleteAllIssueOperations :exec
DELETE FROM issue_operations
`

func (q *Queries) DeleteAllIssueOperations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueOperations)
	return err
}
