// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_all_issue_posts.sql

package issuesdb

import (
	"context"
)

const deleteAllIssuePosts = `-- name: DeleteAllIssuePosts :exec
DELETE FROM issue_posts
`

func (q *Queries) DeleteAllIssuePosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssuePosts)
	return err
}
