// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_all_issues.sql

package issuesdb

import (
	"context"
)

const deleteAllIssues = `-- name: DeleteAllIssues :exec
DELETE FROM issues
`

func (q *Queries) DeleteAllIssues(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssues)
	return err
}
