// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_all_events.sql

package issuesdb

import (
	"context"
)

const deleteAllEvents = `-- name: DeleteAllEvents :exec
DELETE FROM events
`

func (q *Queries) DeleteAllEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEvents)
	return err
}
