// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_all_issue_operation_participants.sql

package issuesdb

import (
	"context"
)

const deleteAllIssueOperationParticipants = `-- name: DeleteAllIssueOperationParticipants :exec
DELETE FROM issue_operation_participants
`

func (q *Queries) DeleteAllIssueOperationParticipants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueOperationParticipants)
	return err
}
