// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_issue.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const getIssue = `-- name: GetIssue :one
SELECT
  i.id,
  COALESCE(c.raw, i.raw) AS raw,
  COALESCE(c.tags_json, i.tags_json) AS tags_json,
  COALESCE(p.created_by, i.created_by) AS created_by,
  COALESCE(p.created_at_unix_nano, i.created_at_unix_nano) AS created_at_unix_nano,
  COALESCE(p.status, i.status) AS status,
  COALESCE(p.closed_at_unix_nano, 0) AS closed_at_unix_nano,
  COALESCE(p.closed_by, '') AS closed_by,
  COALESCE(p.closed_reason, '') AS closed_reason,
  COALESCE(p.closed_reason_note, '') AS closed_reason_note,
  COALESCE(c.tag_scores_json, i.tag_scores_json) AS tag_scores_json,
  COALESCE(c.embedding_vector::text, i.embedding_vector::text, '') AS embedding_text,
  COALESCE(p.assigned_to, i.assigned_to) AS assigned_to,
  COALESCE(ep.status, 'complete') AS enrichment_status,
  COALESCE(ep.error, '') AS enrichment_error,
  COALESCE(ep.target_sequence, 1) AS enrichment_target_sequence
FROM issues i
LEFT JOIN issue_content_projections c ON c.issue_id = i.id
LEFT JOIN issue_lifecycle_projections p ON p.issue_id = i.id
LEFT JOIN issue_enrichment_projections ep ON ep.issue_id = i.id
WHERE i.id = $1
`

type GetIssueRow struct {
	ID                       string
	Raw                      string
	TagsJson                 json.RawMessage
	CreatedBy                string
	CreatedAtUnixNano        int64
	Status                   string
	ClosedAtUnixNano         int64
	ClosedBy                 string
	ClosedReason             string
	ClosedReasonNote         string
	TagScoresJson            json.RawMessage
	EmbeddingText            interface{}
	AssignedTo               string
	EnrichmentStatus         string
	EnrichmentError          string
	EnrichmentTargetSequence int64
}

func (q *Queries) GetIssue(ctx context.Context, id string) (GetIssueRow, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.TagsJson,
		&i.CreatedBy,
		&i.CreatedAtUnixNano,
		&i.Status,
		&i.ClosedAtUnixNano,
		&i.ClosedBy,
		&i.ClosedReason,
		&i.ClosedReasonNote,
		&i.TagScoresJson,
		&i.EmbeddingText,
		&i.AssignedTo,
		&i.EnrichmentStatus,
		&i.EnrichmentError,
		&i.EnrichmentTargetSequence,
	)
	return i, err
}
