// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_issue.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const getIssue = `-- name: GetIssue :one
SELECT id, raw, tags_json, created_by, created_at_unix_nano, status, closed_at_unix_nano, closed_by, tag_scores_json, embedding_json, assigned_to, enrichment_status, enrichment_error, enrichment_target_sequence
FROM issues
WHERE id = $1
`

type GetIssueRow struct {
	ID                       string
	Raw                      string
	TagsJson                 json.RawMessage
	CreatedBy                string
	CreatedAtUnixNano        int64
	Status                   string
	ClosedAtUnixNano         int64
	ClosedBy                 string
	TagScoresJson            json.RawMessage
	EmbeddingJson            json.RawMessage
	AssignedTo               string
	EnrichmentStatus         string
	EnrichmentError          string
	EnrichmentTargetSequence int64
}

func (q *Queries) GetIssue(ctx context.Context, id string) (GetIssueRow, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.TagsJson,
		&i.CreatedBy,
		&i.CreatedAtUnixNano,
		&i.Status,
		&i.ClosedAtUnixNano,
		&i.ClosedBy,
		&i.TagScoresJson,
		&i.EmbeddingJson,
		&i.AssignedTo,
		&i.EnrichmentStatus,
		&i.EnrichmentError,
		&i.EnrichmentTargetSequence,
	)
	return i, err
}
