// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_event.sql

package issuesdb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id,
    kind,
    issue_id,
    created_by,
    created_at_unix_nano,
    body,
    participants_json
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEventParams struct {
	ID                string
	Kind              string
	IssueID           sql.NullString
	CreatedBy         string
	CreatedAtUnixNano int64
	Body              string
	ParticipantsJson  json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Kind,
		arg.IssueID,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Body,
		arg.ParticipantsJson,
	)
	return err
}
