// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_issue.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const insertIssue = `-- name: InsertIssue :exec
INSERT INTO issues (
    id,
    raw,
    tags_json,
    created_by,
    created_at_unix_nano,
    status,
    closed_at_unix_nano,
    closed_by,
    tag_scores_json,
    embedding_json,
    assigned_to
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertIssueParams struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	TagScoresJson     json.RawMessage
	EmbeddingJson     json.RawMessage
	AssignedTo        string
}

func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) error {
	_, err := q.db.ExecContext(ctx, insertIssue,
		arg.ID,
		arg.Raw,
		arg.TagsJson,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Status,
		arg.ClosedAtUnixNano,
		arg.ClosedBy,
		arg.TagScoresJson,
		arg.EmbeddingJson,
		arg.AssignedTo,
	)
	return err
}
