// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_issue_post.sql

package issuesdb

import (
	"context"
)

const insertIssuePost = `-- name: InsertIssuePost :exec
INSERT INTO issue_posts (
    id,
    issue_id,
    raw,
    created_by,
    created_at_unix_nano,
    sequence,
    kind
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIssuePostParams struct {
	ID                string
	IssueID           string
	Raw               string
	CreatedBy         string
	CreatedAtUnixNano int64
	Sequence          int64
	Kind              string
}

func (q *Queries) InsertIssuePost(ctx context.Context, arg InsertIssuePostParams) error {
	_, err := q.db.ExecContext(ctx, insertIssuePost,
		arg.ID,
		arg.IssueID,
		arg.Raw,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Sequence,
		arg.Kind,
	)
	return err
}
