// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_issue_operation.sql

package issuesdb

import (
	"context"
)

const insertIssueOperation = `-- name: InsertIssueOperation :exec
INSERT INTO issue_operations (
    id,
    kind,
    created_by,
    created_at_unix_nano,
    note
) VALUES ($1, $2, $3, $4, $5)
`

type InsertIssueOperationParams struct {
	ID                string
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
}

func (q *Queries) InsertIssueOperation(ctx context.Context, arg InsertIssueOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueOperation,
		arg.ID,
		arg.Kind,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Note,
	)
	return err
}
