// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_issue_link.sql

package issuesdb

import (
	"context"
)

const insertIssueLink = `-- name: InsertIssueLink :exec
INSERT INTO issue_links (
    id,
    source_issue_id,
    target_issue_id,
    type,
    created_by,
    created_at_unix_nano,
    note,
    operation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertIssueLinkParams struct {
	ID                string
	SourceIssueID     string
	TargetIssueID     string
	Type              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
	OperationID       string
}

func (q *Queries) InsertIssueLink(ctx context.Context, arg InsertIssueLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueLink,
		arg.ID,
		arg.SourceIssueID,
		arg.TargetIssueID,
		arg.Type,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Note,
		arg.OperationID,
	)
	return err
}
