// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insert_issue_operation_participant.sql

package issuesdb

import (
	"context"
)

const insertIssueOperationParticipant = `-- name: InsertIssueOperationParticipant :exec
INSERT INTO issue_operation_participants (
    operation_id,
    issue_id,
    role,
    sequence
) VALUES ($1, $2, $3, $4)
`

type InsertIssueOperationParticipantParams struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

func (q *Queries) InsertIssueOperationParticipant(ctx context.Context, arg InsertIssueOperationParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueOperationParticipant,
		arg.OperationID,
		arg.IssueID,
		arg.Role,
		arg.Sequence,
	)
	return err
}
