// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_events.sql

package issuesdb

import (
	"context"
)

const listEvents = `-- name: ListEvents :many
SELECT id, kind, issue_id, created_by, created_at_unix_nano, body, participants_json
FROM events
ORDER BY created_at_unix_nano DESC, id DESC
LIMIT $1
`

func (q *Queries) ListEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IssueID,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Body,
			&i.ParticipantsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
