// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issues_filtered.sql

package issuesdb

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const listIssuesFiltered = `-- name: ListIssuesFiltered :many
SELECT id, raw, tags_json, created_by, created_at_unix_nano, status, closed_at_unix_nano, closed_by, closed_reason, closed_reason_note, tag_scores_json, embedding_json, assigned_to
FROM issues
WHERE (NOT $1::bool OR status = $2::text)
  AND (NOT $3::bool OR LOWER(assigned_to) = LOWER($4::text))
  AND (NOT $5::bool OR id <> $6::text)
  AND (
    NOT $7::bool
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(tags_json) AS tag
      WHERE LOWER(tag) = ANY($8::text[])
    )
    OR EXISTS (
      SELECT 1
      FROM jsonb_to_recordset(tag_scores_json) AS score(tag text, relevance double precision)
      WHERE score.relevance >= 0.3
        AND LOWER(score.tag) = ANY($8::text[])
    )
  )
ORDER BY created_at_unix_nano DESC, id ASC
LIMIT $10
OFFSET $9
`

type ListIssuesFilteredParams struct {
	FilterStatus     bool
	Status           string
	FilterAssignedTo bool
	AssignedTo       string
	FilterExcludeID  bool
	ExcludeID        string
	FilterTags       bool
	Tags             []string
	OffsetCount      int32
	LimitCount       int32
}

type ListIssuesFilteredRow struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	ClosedReason      string
	ClosedReasonNote  string
	TagScoresJson     json.RawMessage
	EmbeddingJson     json.RawMessage
	AssignedTo        string
}

func (q *Queries) ListIssuesFiltered(ctx context.Context, arg ListIssuesFilteredParams) ([]ListIssuesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesFiltered,
		arg.FilterStatus,
		arg.Status,
		arg.FilterAssignedTo,
		arg.AssignedTo,
		arg.FilterExcludeID,
		arg.ExcludeID,
		arg.FilterTags,
		pq.Array(arg.Tags),
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesFilteredRow
	for rows.Next() {
		var i ListIssuesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.TagsJson,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Status,
			&i.ClosedAtUnixNano,
			&i.ClosedBy,
			&i.ClosedReason,
			&i.ClosedReasonNote,
			&i.TagScoresJson,
			&i.EmbeddingJson,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
