// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_issue_links_for_issues.sql

package issuesdb

import (
	"context"

	"github.com/lib/pq"
)

const listIssueLinksForIssues = `-- name: ListIssueLinksForIssues :many
SELECT id, source_issue_id, target_issue_id, type, created_by, created_at_unix_nano, note, operation_id
FROM issue_links
WHERE source_issue_id = ANY($1::text[]) OR target_issue_id = ANY($1::text[])
ORDER BY created_at_unix_nano DESC, id DESC
`

func (q *Queries) ListIssueLinksForIssues(ctx context.Context, dollar_1 []string) ([]IssueLink, error) {
	rows, err := q.db.QueryContext(ctx, listIssueLinksForIssues, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueLink
	for rows.Next() {
		var i IssueLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceIssueID,
			&i.TargetIssueID,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Note,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
