// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issue_references_by_ids.sql

package issuesdb

import (
	"context"

	"github.com/lib/pq"
)

const listIssueReferencesByIDs = `-- name: ListIssueReferencesByIDs :many
SELECT id, raw, status
FROM issues
WHERE id = ANY($1::text[])
ORDER BY id ASC
`

type ListIssueReferencesByIDsRow struct {
	ID     string
	Raw    string
	Status string
}

func (q *Queries) ListIssueReferencesByIDs(ctx context.Context, ids []string) ([]ListIssueReferencesByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueReferencesByIDs, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueReferencesByIDsRow
	for rows.Next() {
		var i ListIssueReferencesByIDsRow
		if err := rows.Scan(&i.ID, &i.Raw, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
