// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_events_by_kind_before.sql

package issuesdb

import (
	"context"
)

const listEventsByKindBefore = `-- name: ListEventsByKindBefore :many
SELECT id, kind, issue_id, created_by, created_at_unix_nano, body, participants_json
FROM events
WHERE kind = $1
  AND (created_at_unix_nano < $2
       OR (created_at_unix_nano = $2 AND id < $3))
ORDER BY created_at_unix_nano DESC, id DESC
LIMIT $4
`

type ListEventsByKindBeforeParams struct {
	Kind              string
	CreatedAtUnixNano int64
	ID                string
	Limit             int32
}

func (q *Queries) ListEventsByKindBefore(ctx context.Context, arg ListEventsByKindBeforeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByKindBefore,
		arg.Kind,
		arg.CreatedAtUnixNano,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IssueID,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Body,
			&i.ParticipantsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
