// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_issue_posts_for_issues.sql

package issuesdb

import (
	"context"

	"github.com/lib/pq"
)

const listIssuePostsForIssues = `-- name: ListIssuePostsForIssues :many
SELECT id, issue_id, raw, created_by, created_at_unix_nano, sequence, kind
FROM issue_posts
WHERE issue_id = ANY($1::text[])
ORDER BY issue_id ASC, sequence ASC, created_at_unix_nano ASC, id ASC
`

func (q *Queries) ListIssuePostsForIssues(ctx context.Context, dollar_1 []string) ([]IssuePost, error) {
	rows, err := q.db.QueryContext(ctx, listIssuePostsForIssues, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuePost
	for rows.Next() {
		var i IssuePost
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Raw,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Sequence,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
