// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_events_before.sql

package issuesdb

import (
	"context"
)

const listEventsBefore = `-- name: ListEventsBefore :many
SELECT id, kind, issue_id, created_by, created_at_unix_nano, body, participants_json
FROM events
WHERE created_at_unix_nano < $1
   OR (created_at_unix_nano = $1 AND id < $2)
ORDER BY created_at_unix_nano DESC, id DESC
LIMIT $3
`

type ListEventsBeforeParams struct {
	CreatedAtUnixNano int64
	ID                string
	Limit             int32
}

func (q *Queries) ListEventsBefore(ctx context.Context, arg ListEventsBeforeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBefore, arg.CreatedAtUnixNano, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.IssueID,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Body,
			&i.ParticipantsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
