// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_tags.sql

package issuesdb

import (
	"context"
	"database/sql"
)

const listTags = `-- name: ListTags :many
SELECT name, description, created_at_unix_nano,
       COALESCE(embedding_vector::text, '') AS embedding_text,
       specificity, specificity_llm, specificity_embedding, specificity_computed_at
FROM tags
ORDER BY name ASC
`

type ListTagsRow struct {
	Name                  string
	Description           string
	CreatedAtUnixNano     int64
	EmbeddingText         interface{}
	Specificity           sql.NullFloat64
	SpecificityLlm        sql.NullFloat64
	SpecificityEmbedding  sql.NullFloat64
	SpecificityComputedAt sql.NullTime
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAtUnixNano,
			&i.EmbeddingText,
			&i.Specificity,
			&i.SpecificityLlm,
			&i.SpecificityEmbedding,
			&i.SpecificityComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
