// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issue_posts.sql

package issuesdb

import (
	"context"
)

const listIssuePosts = `-- name: ListIssuePosts :many
SELECT id, issue_id, raw, created_by, created_at_unix_nano, sequence, kind
FROM issue_posts
WHERE issue_id = $1
ORDER BY sequence ASC, created_at_unix_nano ASC, id ASC
`

func (q *Queries) ListIssuePosts(ctx context.Context, issueID string) ([]IssuePost, error) {
	rows, err := q.db.QueryContext(ctx, listIssuePosts, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuePost
	for rows.Next() {
		var i IssuePost
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Raw,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Sequence,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
