// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_issue_operation_participants_for_operations.sql

package issuesdb

import (
	"context"

	"github.com/lib/pq"
)

const listIssueOperationParticipantsForOperations = `-- name: ListIssueOperationParticipantsForOperations :many
SELECT operation_id, issue_id, role, sequence
FROM issue_operation_participants
WHERE operation_id = ANY($1::text[])
ORDER BY operation_id ASC, sequence ASC, issue_id ASC
`

func (q *Queries) ListIssueOperationParticipantsForOperations(ctx context.Context, dollar_1 []string) ([]IssueOperationParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationParticipantsForOperations, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueOperationParticipant
	for rows.Next() {
		var i IssueOperationParticipant
		if err := rows.Scan(
			&i.OperationID,
			&i.IssueID,
			&i.Role,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
