// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issue_operation_participants_for_operations.sql

package issuesdb

import (
	"context"

	"github.com/lib/pq"
)

const listIssueOperationParticipantsForOperations = `-- name: ListIssueOperationParticipantsForOperations :many
SELECT operation_id, issue_id, role, sequence
FROM issue_operation_participants
WHERE operation_id = ANY($1::text[])
ORDER BY operation_id ASC, sequence ASC, issue_id ASC
`

type ListIssueOperationParticipantsForOperationsRow struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

func (q *Queries) ListIssueOperationParticipantsForOperations(
	ctx context.Context,
	operationIDs []string,
) ([]ListIssueOperationParticipantsForOperationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationParticipantsForOperations, pq.Array(operationIDs))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueOperationParticipantsForOperationsRow
	for rows.Next() {
		var i ListIssueOperationParticipantsForOperationsRow
		if err := rows.Scan(&i.OperationID, &i.IssueID, &i.Role, &i.Sequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
