// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issues_filtered.sql

package issuesdb

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const listIssuesFiltered = `-- name: ListIssuesFiltered :many
SELECT
  i.id,
  COALESCE(c.raw, i.raw) AS raw,
  COALESCE(c.tags_json, i.tags_json) AS tags_json,
  COALESCE(p.created_by, i.created_by) AS created_by,
  COALESCE(p.created_at_unix_nano, i.created_at_unix_nano) AS created_at_unix_nano,
  COALESCE(p.status, i.status) AS status,
  COALESCE(p.closed_at_unix_nano, i.closed_at_unix_nano) AS closed_at_unix_nano,
  COALESCE(p.closed_by, i.closed_by) AS closed_by,
  COALESCE(p.closed_reason, i.closed_reason) AS closed_reason,
  COALESCE(p.closed_reason_note, i.closed_reason_note) AS closed_reason_note,
  COALESCE(c.tag_scores_json, i.tag_scores_json) AS tag_scores_json,
  COALESCE(c.embedding_vector::text, i.embedding_vector::text, '') AS embedding_text,
  COALESCE(p.assigned_to, i.assigned_to) AS assigned_to
FROM issues i
LEFT JOIN issue_content_projections c ON c.issue_id = i.id
LEFT JOIN issue_lifecycle_projections p ON p.issue_id = i.id
WHERE (NOT $1::bool OR COALESCE(p.status, i.status) = $2::text)
  AND (NOT $3::bool OR LOWER(COALESCE(p.assigned_to, i.assigned_to)) = LOWER($4::text))
  AND (NOT $5::bool OR i.id <> $6::text)
  AND (
    NOT $7::bool
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(COALESCE(c.tags_json, i.tags_json)) AS tag
      WHERE LOWER(tag) = ANY($8::text[])
    )
    OR EXISTS (
      SELECT 1
      FROM jsonb_to_recordset(COALESCE(c.tag_scores_json, i.tag_scores_json)) AS score(tag text, relevance double precision)
      WHERE score.relevance >= 0.3
        AND LOWER(score.tag) = ANY($8::text[])
    )
  )
ORDER BY COALESCE(p.created_at_unix_nano, i.created_at_unix_nano) DESC, i.id ASC
LIMIT $10
OFFSET $9
`

type ListIssuesFilteredParams struct {
	FilterStatus     bool
	Status           string
	FilterAssignedTo bool
	AssignedTo       string
	FilterExcludeID  bool
	ExcludeID        string
	FilterTags       bool
	Tags             []string
	OffsetCount      int32
	LimitCount       int32
}

type ListIssuesFilteredRow struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	ClosedReason      string
	ClosedReasonNote  string
	TagScoresJson     json.RawMessage
	EmbeddingText     interface{}
	AssignedTo        string
}

func (q *Queries) ListIssuesFiltered(ctx context.Context, arg ListIssuesFilteredParams) ([]ListIssuesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssuesFiltered,
		arg.FilterStatus,
		arg.Status,
		arg.FilterAssignedTo,
		arg.AssignedTo,
		arg.FilterExcludeID,
		arg.ExcludeID,
		arg.FilterTags,
		pq.Array(arg.Tags),
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesFilteredRow
	for rows.Next() {
		var i ListIssuesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.TagsJson,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Status,
			&i.ClosedAtUnixNano,
			&i.ClosedBy,
			&i.ClosedReason,
			&i.ClosedReasonNote,
			&i.TagScoresJson,
			&i.EmbeddingText,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
