// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: list_issue_operations_for_issue.sql

package issuesdb

import (
	"context"
)

const listIssueOperationsForIssue = `-- name: ListIssueOperationsForIssue :many
SELECT DISTINCT o.id, o.kind, o.created_by, o.created_at_unix_nano, o.note
FROM issue_operations o
JOIN issue_operation_participants p ON p.operation_id = o.id
WHERE p.issue_id = $1
ORDER BY o.created_at_unix_nano DESC, o.id DESC
`

func (q *Queries) ListIssueOperationsForIssue(ctx context.Context, issueID string) ([]IssueOperation, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationsForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueOperation
	for rows.Next() {
		var i IssueOperation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
