// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_issue_operation_participants.sql

package issuesdb

import (
	"context"
)

const listIssueOperationParticipants = `-- name: ListIssueOperationParticipants :many
SELECT operation_id, issue_id, role, sequence
FROM issue_operation_participants
WHERE operation_id = $1
ORDER BY sequence ASC, issue_id ASC
`

func (q *Queries) ListIssueOperationParticipants(ctx context.Context, operationID string) ([]IssueOperationParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationParticipants, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueOperationParticipant
	for rows.Next() {
		var i IssueOperationParticipant
		if err := rows.Scan(
			&i.OperationID,
			&i.IssueID,
			&i.Role,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
