// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_tags.sql

package issuesdb

import (
	"context"
)

const listTags = `-- name: ListTags :many
SELECT name, description, created_at_unix_nano, embedding_json,
       specificity, specificity_llm, specificity_embedding, specificity_computed_at
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAtUnixNano,
			&i.EmbeddingJson,
			&i.Specificity,
			&i.SpecificityLlm,
			&i.SpecificityEmbedding,
			&i.SpecificityComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
