// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package issuesdb

type Issue struct {
	ID                string
	Raw               string
	TagsJson          string
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	TagScoresJson     string
	EmbeddingJson     string
	AssignedTo        string
}

type IssueLink struct {
	ID                string
	SourceIssueID     string
	TargetIssueID     string
	Type              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
	OperationID       string
}

type IssueOperation struct {
	ID                string
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
}

type IssueOperationParticipant struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

type IssuePost struct {
	ID                string
	IssueID           string
	Raw               string
	CreatedBy         string
	CreatedAtUnixNano int64
	Sequence          int64
	Kind              string
}

type Metadata struct {
	Key   string
	Value string
}

type Tag struct {
	Name              string
	Description       string
	CreatedAtUnixNano int64
	EmbeddingJson     string
}
