// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package issuesdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type ApiToken struct {
	ID                 string
	UserID             string
	TokenHash          string
	TokenPrefix        string
	CreatedAtUnixNano  int64
	RevokedAtUnixNano  int64
	Name               string
	LastUsedAtUnixNano int64
}

type ApiTokenFact struct {
	ID                string
	TokenID           string
	UserID            string
	Sequence          int64
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	PayloadJson       json.RawMessage
	Source            string
	SourceID          string
	Inferred          bool
}

type AppendOnlyMigrationCheckpoint struct {
	Name              string
	Phase             string
	CursorJson        json.RawMessage
	SummaryJson       json.RawMessage
	UpdatedAtUnixNano int64
}

type AppendOnlyParityRun struct {
	ID                string
	Domain            string
	Status            string
	DetailsJson       json.RawMessage
	CreatedAtUnixNano int64
}

type AuthAccount struct {
	ID                string
	UserID            string
	Provider          string
	ProviderUserID    string
	CreatedAtUnixNano int64
}

type CurationProposal struct {
	ID                string
	Kind              string
	PayloadJson       json.RawMessage
	Status            string
	Rationale         string
	Confidence        float64
	SourceRefsJson    json.RawMessage
	CreatedBy         string
	ReviewedBy        string
	ResultRef         string
	CreatedAtUnixNano int64
	UpdatedAtUnixNano int64
}

type CustomRegion struct {
	ID                string
	Label             string
	Description       string
	DefinitionJson    json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	UpdatedAtUnixNano int64
}

type DismissedTagMerge struct {
	ID            int64
	CanonicalName string
	AliasName     string
	DismissedAt   time.Time
}

type Event struct {
	ID                string
	Kind              string
	IssueID           sql.NullString
	CreatedBy         string
	CreatedAtUnixNano int64
	Body              string
	ParticipantsJson  json.RawMessage
}

type Issue struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	TagScoresJson     json.RawMessage
	AssignedTo        string
	EmbeddingVector   interface{}
}

type IssueContentFact struct {
	ID                string
	IssueID           string
	Sequence          int64
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	PayloadJson       json.RawMessage
	Source            string
	SourceID          string
	Inferred          bool
}

type IssueContentProjection struct {
	IssueID           string
	Raw               string
	TagsJson          json.RawMessage
	TagScoresJson     json.RawMessage
	EmbeddingVector   interface{}
	LastEventID       string
	EventCount        int64
	UpdatedAtUnixNano int64
	SearchTitle       string
	SearchBody        string
	SearchTags        string
}

type IssueEnrichmentEvent struct {
	ID                string
	IssueID           string
	TargetSequence    int64
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	PayloadJson       json.RawMessage
}

type IssueEnrichmentJob struct {
	IssueID                string
	TargetSequence         int64
	LeaseExpiresAtUnixNano int64
	AttemptCount           int64
	CreatedAtUnixNano      int64
	UpdatedAtUnixNano      int64
}

type IssueEnrichmentProjection struct {
	IssueID                string
	Status                 string
	Error                  string
	TargetSequence         int64
	AttemptCount           int64
	LeaseExpiresAtUnixNano int64
	LatestEventID          string
	UpdatedAtUnixNano      int64
}

type IssueLifecycleFact struct {
	ID                string
	IssueID           string
	Sequence          int64
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	PayloadJson       json.RawMessage
	Source            string
	SourceID          string
	Inferred          bool
}

type IssueLifecycleProjection struct {
	IssueID           string
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  sql.NullInt64
	ClosedBy          sql.NullString
	ClosedReason      sql.NullString
	ClosedReasonNote  sql.NullString
	AssignedTo        string
	LastFactID        string
	FactCount         int64
	UpdatedAtUnixNano int64
}

type IssueLink struct {
	ID                string
	SourceIssueID     string
	TargetIssueID     string
	Type              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
	OperationID       string
}

type IssueOperation struct {
	ID                string
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
}

type IssueOperationParticipant struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

type IssuePost struct {
	ID                string
	IssueID           string
	Raw               string
	CreatedBy         string
	CreatedAtUnixNano int64
	Sequence          int64
	Kind              string
}

type IssueSnapshot struct {
	IssueID           string
	Sequence          int64
	Raw               string
	TagsJson          json.RawMessage
	TagScoresJson     json.RawMessage
	EmbeddingJson     json.RawMessage
	CreatedAtUnixNano int64
}

type MapProjection struct {
	Revision          int64
	PayloadJson       json.RawMessage
	CreatedAtUnixNano int64
}

type Memory struct {
	ID                       string
	Title                    string
	Body                     string
	Kind                     string
	AnchorTagsJson           json.RawMessage
	AnchorRegion             string
	TagScoresJson            json.RawMessage
	EmbeddingVector          interface{}
	Status                   string
	SupersededBy             string
	Source                   string
	SourceIssueIdsJson       json.RawMessage
	Confidence               float64
	CreatedBy                string
	CreatedAtUnixNano        int64
	UpdatedAtUnixNano        int64
	LastReinforcedAtUnixNano int64
	ReinforcementCount       int64
	SubjectTag               string
}

type MemoryProposal struct {
	ID                 string
	Title              string
	Body               string
	Kind               string
	AnchorTagsJson     json.RawMessage
	AnchorRegion       string
	SourceIssueIdsJson json.RawMessage
	Confidence         float64
	Status             string
	Rationale          string
	AcceptedMemoryID   string
	CreatedAtUnixNano  int64
	UpdatedAtUnixNano  int64
	SubjectTag         string
}

type Session struct {
	ID                string
	UserID            string
	TokenHash         string
	ExpiresAtUnixNano int64
	CreatedAtUnixNano int64
}

type Tag struct {
	Name                  string
	Description           string
	CreatedAtUnixNano     int64
	Specificity           sql.NullFloat64
	SpecificityLlm        sql.NullFloat64
	SpecificityEmbedding  sql.NullFloat64
	SpecificityComputedAt sql.NullTime
	EmbeddingVector       interface{}
}

type TagCooccurrenceProjection struct {
	ID                 string
	Revision           int64
	IssueCount         int64
	TagCount           int32
	BodyJson           json.RawMessage
	ComputedAtUnixNano int64
}

type TagEvent struct {
	ID                string
	TagName           string
	Sequence          int64
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	PayloadJson       json.RawMessage
	Source            string
	SourceID          string
	Inferred          bool
}

type TagMergeHistory struct {
	ID            int64
	CanonicalName string
	AliasName     string
	MergedAt      time.Time
	MergedBy      string
}

type TagProjection struct {
	Name                  string
	Description           string
	CreatedAtUnixNano     int64
	EmbeddingVector       interface{}
	Specificity           sql.NullFloat64
	SpecificityLlm        sql.NullFloat64
	SpecificityEmbedding  sql.NullFloat64
	SpecificityComputedAt sql.NullTime
	Status                string
	CanonicalName         string
	LastEventID           string
	EventCount            int64
	UpdatedAtUnixNano     int64
}

type User struct {
	ID                string
	Login             string
	DisplayName       string
	AvatarUrl         string
	Email             string
	CreatedAtUnixNano int64
	UpdatedAtUnixNano int64
}

type UserProfileFact struct {
	ID                 string
	UserID             string
	Sequence           int64
	Login              string
	DisplayName        string
	AvatarUrl          string
	Email              string
	ObservedAtUnixNano int64
	Source             string
	SourceID           string
	Inferred           bool
}
