// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package issuesdb

import (
	"encoding/json"
)

type ApiToken struct {
	ID                string
	UserID            string
	TokenHash         string
	TokenPrefix       string
	CreatedAtUnixNano int64
	RevokedAtUnixNano int64
}

type AuthAccount struct {
	ID                string
	UserID            string
	Provider          string
	ProviderUserID    string
	CreatedAtUnixNano int64
}

type Event struct {
	ID                string
	Kind              string
	IssueID           string
	CreatedBy         string
	CreatedAtUnixNano int64
	Body              string
	ParticipantsJson  json.RawMessage
}

type Issue struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	TagScoresJson     json.RawMessage
	EmbeddingJson     json.RawMessage
	AssignedTo        string
}

type IssueLink struct {
	ID                string
	SourceIssueID     string
	TargetIssueID     string
	Type              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
	OperationID       string
}

type IssueOperation struct {
	ID                string
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
}

type IssueOperationParticipant struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

type IssuePost struct {
	ID                string
	IssueID           string
	Raw               string
	CreatedBy         string
	CreatedAtUnixNano int64
	Sequence          int64
	Kind              string
}

type Session struct {
	ID                string
	UserID            string
	TokenHash         string
	ExpiresAtUnixNano int64
	CreatedAtUnixNano int64
}

type Tag struct {
	Name              string
	Description       string
	CreatedAtUnixNano int64
	EmbeddingJson     json.RawMessage
}

type User struct {
	ID                string
	Login             string
	DisplayName       string
	AvatarUrl         string
	Email             string
	CreatedAtUnixNano int64
	UpdatedAtUnixNano int64
}
