// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const assignIssue = `-- name: AssignIssue :exec
UPDATE issues SET assigned_to = $1 WHERE id = $2
`

type AssignIssueParams struct {
	AssignedTo string
	ID         string
}

func (q *Queries) AssignIssue(ctx context.Context, arg AssignIssueParams) error {
	_, err := q.db.ExecContext(ctx, assignIssue, arg.AssignedTo, arg.ID)
	return err
}

const closeIssue = `-- name: CloseIssue :exec
UPDATE issues
SET status = 'closed',
    closed_at_unix_nano = $1,
    closed_by = $2
WHERE id = $3
`

type CloseIssueParams struct {
	ClosedAtUnixNano int64
	ClosedBy         string
	ID               string
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) error {
	_, err := q.db.ExecContext(ctx, closeIssue, arg.ClosedAtUnixNano, arg.ClosedBy, arg.ID)
	return err
}

const deleteAllIssueLinks = `-- name: DeleteAllIssueLinks :exec
DELETE FROM issue_links
`

func (q *Queries) DeleteAllIssueLinks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueLinks)
	return err
}

const deleteAllIssueOperationParticipants = `-- name: DeleteAllIssueOperationParticipants :exec
DELETE FROM issue_operation_participants
`

func (q *Queries) DeleteAllIssueOperationParticipants(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueOperationParticipants)
	return err
}

const deleteAllIssueOperations = `-- name: DeleteAllIssueOperations :exec
DELETE FROM issue_operations
`

func (q *Queries) DeleteAllIssueOperations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssueOperations)
	return err
}

const deleteAllIssuePosts = `-- name: DeleteAllIssuePosts :exec
DELETE FROM issue_posts
`

func (q *Queries) DeleteAllIssuePosts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssuePosts)
	return err
}

const deleteAllIssues = `-- name: DeleteAllIssues :exec
DELETE FROM issues
`

func (q *Queries) DeleteAllIssues(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllIssues)
	return err
}

const getIssue = `-- name: GetIssue :one
SELECT id, raw, tags_json, created_by, created_at_unix_nano, status, closed_at_unix_nano, closed_by, tag_scores_json, embedding_json, assigned_to
FROM issues
WHERE id = $1
`

func (q *Queries) GetIssue(ctx context.Context, id string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Raw,
		&i.TagsJson,
		&i.CreatedBy,
		&i.CreatedAtUnixNano,
		&i.Status,
		&i.ClosedAtUnixNano,
		&i.ClosedBy,
		&i.TagScoresJson,
		&i.EmbeddingJson,
		&i.AssignedTo,
	)
	return i, err
}

const insertIssue = `-- name: InsertIssue :exec
INSERT INTO issues (
    id,
    raw,
    tags_json,
    created_by,
    created_at_unix_nano,
    status,
    closed_at_unix_nano,
    closed_by,
    tag_scores_json,
    embedding_json,
    assigned_to
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertIssueParams struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	TagScoresJson     json.RawMessage
	EmbeddingJson     json.RawMessage
	AssignedTo        string
}

func (q *Queries) InsertIssue(ctx context.Context, arg InsertIssueParams) error {
	_, err := q.db.ExecContext(ctx, insertIssue,
		arg.ID,
		arg.Raw,
		arg.TagsJson,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Status,
		arg.ClosedAtUnixNano,
		arg.ClosedBy,
		arg.TagScoresJson,
		arg.EmbeddingJson,
		arg.AssignedTo,
	)
	return err
}

const insertIssueLink = `-- name: InsertIssueLink :exec
INSERT INTO issue_links (
    id,
    source_issue_id,
    target_issue_id,
    type,
    created_by,
    created_at_unix_nano,
    note,
    operation_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertIssueLinkParams struct {
	ID                string
	SourceIssueID     string
	TargetIssueID     string
	Type              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
	OperationID       string
}

func (q *Queries) InsertIssueLink(ctx context.Context, arg InsertIssueLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueLink,
		arg.ID,
		arg.SourceIssueID,
		arg.TargetIssueID,
		arg.Type,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Note,
		arg.OperationID,
	)
	return err
}

const insertIssueOperation = `-- name: InsertIssueOperation :exec
INSERT INTO issue_operations (
    id,
    kind,
    created_by,
    created_at_unix_nano,
    note
) VALUES ($1, $2, $3, $4, $5)
`

type InsertIssueOperationParams struct {
	ID                string
	Kind              string
	CreatedBy         string
	CreatedAtUnixNano int64
	Note              string
}

func (q *Queries) InsertIssueOperation(ctx context.Context, arg InsertIssueOperationParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueOperation,
		arg.ID,
		arg.Kind,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Note,
	)
	return err
}

const insertIssueOperationParticipant = `-- name: InsertIssueOperationParticipant :exec
INSERT INTO issue_operation_participants (
    operation_id,
    issue_id,
    role,
    sequence
) VALUES ($1, $2, $3, $4)
`

type InsertIssueOperationParticipantParams struct {
	OperationID string
	IssueID     string
	Role        string
	Sequence    int64
}

func (q *Queries) InsertIssueOperationParticipant(ctx context.Context, arg InsertIssueOperationParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertIssueOperationParticipant,
		arg.OperationID,
		arg.IssueID,
		arg.Role,
		arg.Sequence,
	)
	return err
}

const insertIssuePost = `-- name: InsertIssuePost :exec
INSERT INTO issue_posts (
    id,
    issue_id,
    raw,
    created_by,
    created_at_unix_nano,
    sequence,
    kind
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIssuePostParams struct {
	ID                string
	IssueID           string
	Raw               string
	CreatedBy         string
	CreatedAtUnixNano int64
	Sequence          int64
	Kind              string
}

func (q *Queries) InsertIssuePost(ctx context.Context, arg InsertIssuePostParams) error {
	_, err := q.db.ExecContext(ctx, insertIssuePost,
		arg.ID,
		arg.IssueID,
		arg.Raw,
		arg.CreatedBy,
		arg.CreatedAtUnixNano,
		arg.Sequence,
		arg.Kind,
	)
	return err
}

const listIssueLinksForIssue = `-- name: ListIssueLinksForIssue :many
SELECT id, source_issue_id, target_issue_id, type, created_by, created_at_unix_nano, note, operation_id
FROM issue_links
WHERE source_issue_id = $1 OR target_issue_id = $2
ORDER BY created_at_unix_nano DESC, id DESC
`

type ListIssueLinksForIssueParams struct {
	SourceIssueID string
	TargetIssueID string
}

func (q *Queries) ListIssueLinksForIssue(ctx context.Context, arg ListIssueLinksForIssueParams) ([]IssueLink, error) {
	rows, err := q.db.QueryContext(ctx, listIssueLinksForIssue, arg.SourceIssueID, arg.TargetIssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueLink
	for rows.Next() {
		var i IssueLink
		if err := rows.Scan(
			&i.ID,
			&i.SourceIssueID,
			&i.TargetIssueID,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Note,
			&i.OperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueOperationParticipants = `-- name: ListIssueOperationParticipants :many
SELECT operation_id, issue_id, role, sequence
FROM issue_operation_participants
WHERE operation_id = $1
ORDER BY sequence ASC, issue_id ASC
`

func (q *Queries) ListIssueOperationParticipants(ctx context.Context, operationID string) ([]IssueOperationParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationParticipants, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueOperationParticipant
	for rows.Next() {
		var i IssueOperationParticipant
		if err := rows.Scan(
			&i.OperationID,
			&i.IssueID,
			&i.Role,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueOperationsForIssue = `-- name: ListIssueOperationsForIssue :many
SELECT DISTINCT o.id, o.kind, o.created_by, o.created_at_unix_nano, o.note
FROM issue_operations o
JOIN issue_operation_participants p ON p.operation_id = o.id
WHERE p.issue_id = $1
ORDER BY o.created_at_unix_nano DESC, o.id DESC
`

func (q *Queries) ListIssueOperationsForIssue(ctx context.Context, issueID string) ([]IssueOperation, error) {
	rows, err := q.db.QueryContext(ctx, listIssueOperationsForIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueOperation
	for rows.Next() {
		var i IssueOperation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuePosts = `-- name: ListIssuePosts :many
SELECT id, issue_id, raw, created_by, created_at_unix_nano, sequence, kind
FROM issue_posts
WHERE issue_id = $1
ORDER BY sequence ASC, created_at_unix_nano ASC, id ASC
`

func (q *Queries) ListIssuePosts(ctx context.Context, issueID string) ([]IssuePost, error) {
	rows, err := q.db.QueryContext(ctx, listIssuePosts, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssuePost
	for rows.Next() {
		var i IssuePost
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Raw,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Sequence,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT id, raw, tags_json, created_by, created_at_unix_nano, status, closed_at_unix_nano, closed_by, tag_scores_json, embedding_json, assigned_to
FROM issues
ORDER BY created_at_unix_nano DESC, id ASC
`

func (q *Queries) ListIssues(ctx context.Context) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.TagsJson,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Status,
			&i.ClosedAtUnixNano,
			&i.ClosedBy,
			&i.TagScoresJson,
			&i.EmbeddingJson,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT name, description, created_at_unix_nano, embedding_json
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.Name,
			&i.Description,
			&i.CreatedAtUnixNano,
			&i.EmbeddingJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextIssueOperationSeq = `-- name: NextIssueOperationSeq :one
SELECT nextval('issue_operation_seq')
`

func (q *Queries) NextIssueOperationSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextIssueOperationSeq)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const nextIssueSeq = `-- name: NextIssueSeq :one
SELECT nextval('issue_seq')
`

func (q *Queries) NextIssueSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextIssueSeq)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}

const reopenIssue = `-- name: ReopenIssue :exec
UPDATE issues
SET status = 'open',
    closed_at_unix_nano = 0,
    closed_by = ''
WHERE id = $1
`

func (q *Queries) ReopenIssue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, reopenIssue, id)
	return err
}

const resetIssueOperationSeq = `-- name: ResetIssueOperationSeq :exec
SELECT setval('issue_operation_seq', 1, false)
`

func (q *Queries) ResetIssueOperationSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetIssueOperationSeq)
	return err
}

const resetIssueSeq = `-- name: ResetIssueSeq :exec
SELECT setval('issue_seq', 1, false)
`

func (q *Queries) ResetIssueSeq(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetIssueSeq)
	return err
}

const setIssueSeq = `-- name: SetIssueSeq :exec
SELECT setval('issue_seq', $1, true)
`

func (q *Queries) SetIssueSeq(ctx context.Context, setval int64) error {
	_, err := q.db.ExecContext(ctx, setIssueSeq, setval)
	return err
}

const updateIssueRefinement = `-- name: UpdateIssueRefinement :exec
UPDATE issues
SET raw = $1,
    tags_json = $2,
    tag_scores_json = $3,
    embedding_json = $4
WHERE id = $5
`

type UpdateIssueRefinementParams struct {
	Raw           string
	TagsJson      json.RawMessage
	TagScoresJson json.RawMessage
	EmbeddingJson json.RawMessage
	ID            string
}

func (q *Queries) UpdateIssueRefinement(ctx context.Context, arg UpdateIssueRefinementParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueRefinement,
		arg.Raw,
		arg.TagsJson,
		arg.TagScoresJson,
		arg.EmbeddingJson,
		arg.ID,
	)
	return err
}

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (name, description, created_at_unix_nano, embedding_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT(name) DO UPDATE SET
    description = CASE
        WHEN excluded.description <> '' THEN excluded.description
        ELSE tags.description
    END,
    embedding_json = CASE
        WHEN excluded.embedding_json <> '[]' THEN excluded.embedding_json
        ELSE tags.embedding_json
    END
`

type UpsertTagParams struct {
	Name              string
	Description       string
	CreatedAtUnixNano int64
	EmbeddingJson     json.RawMessage
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.Name,
		arg.Description,
		arg.CreatedAtUnixNano,
		arg.EmbeddingJson,
	)
	return err
}
