// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reopen_issue.sql

package issuesdb

import (
	"context"
)

const reopenIssue = `-- name: ReopenIssue :exec
UPDATE issues
SET status = 'open',
    closed_at_unix_nano = 0,
    closed_by = '',
    closed_reason = '',
    closed_reason_note = ''
WHERE id = $1
`

func (q *Queries) ReopenIssue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, reopenIssue, id)
	return err
}
