// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_issues_by_text.sql

package issuesdb

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const searchIssuesByText = `-- name: SearchIssuesByText :many
SELECT
  i.id,
  COALESCE(c.raw, i.raw) AS raw,
  COALESCE(c.tags_json, i.tags_json) AS tags_json,
  COALESCE(p.created_by, i.created_by) AS created_by,
  COALESCE(p.created_at_unix_nano, i.created_at_unix_nano) AS created_at_unix_nano,
  COALESCE(p.status, i.status) AS status,
  COALESCE(p.closed_at_unix_nano, i.closed_at_unix_nano) AS closed_at_unix_nano,
  COALESCE(p.closed_by, i.closed_by) AS closed_by,
  COALESCE(p.closed_reason, i.closed_reason) AS closed_reason,
  COALESCE(p.closed_reason_note, i.closed_reason_note) AS closed_reason_note,
  COALESCE(c.tag_scores_json, i.tag_scores_json) AS tag_scores_json,
  COALESCE(c.embedding_vector::text, i.embedding_vector::text, '') AS embedding_text,
  COALESCE(p.assigned_to, i.assigned_to) AS assigned_to,
  (paradedb.score(c.*)
    * (0.3 + 0.7 * EXP(-0.693147 * (EXTRACT(EPOCH FROM NOW()) * 1e9 - c.updated_at_unix_nano) / (90.0 * 86400 * 1e9)))
    * CASE COALESCE(p.closed_reason, i.closed_reason, '')
        WHEN 'duplicate' THEN 0.3
        WHEN 'stale'     THEN 0.5
        WHEN 'wont_fix'  THEN 0.5
        WHEN 'by_design' THEN 0.7
        WHEN 'fixed'     THEN 0.7
        WHEN ''          THEN 1.0
        ELSE 0.8
      END
  )::float8 AS text_score
FROM issue_content_projections c
JOIN issues i ON i.id = c.issue_id
LEFT JOIN issue_lifecycle_projections p ON p.issue_id = i.id
WHERE (
    paradedb.search_with_match_disjunction(c.search_title, $1)
    OR paradedb.search_with_match_disjunction(c.search_body, $1)
    OR paradedb.search_with_match_disjunction(c.search_tags, $1)
  )
  AND (NOT $2::bool OR COALESCE(p.status, i.status) = $3::text)
  AND (NOT $4::bool OR LOWER(COALESCE(p.assigned_to, i.assigned_to)) = LOWER($5::text))
  AND (NOT $6::bool OR i.id <> $7::text)
  AND (
    NOT $8::bool
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(COALESCE(c.tags_json, i.tags_json)) AS tag
      WHERE LOWER(tag) = ANY($9::text[])
    )
    OR EXISTS (
      SELECT 1
      FROM jsonb_to_recordset(COALESCE(c.tag_scores_json, i.tag_scores_json)) AS score(tag text, relevance double precision)
      WHERE score.relevance >= 0.3
        AND LOWER(score.tag) = ANY($9::text[])
    )
  )
ORDER BY text_score DESC, COALESCE(p.created_at_unix_nano, i.created_at_unix_nano) DESC, i.id ASC
LIMIT $11
OFFSET $10
`

type SearchIssuesByTextParams struct {
	QueryText        interface{}
	FilterStatus     bool
	Status           string
	FilterAssignedTo bool
	AssignedTo       string
	FilterExcludeID  bool
	ExcludeID        string
	FilterTags       bool
	Tags             []string
	OffsetCount      int32
	LimitCount       int32
}

type SearchIssuesByTextRow struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	ClosedReason      string
	ClosedReasonNote  string
	TagScoresJson     json.RawMessage
	EmbeddingText     interface{}
	AssignedTo        string
	TextScore         float64
}

func (q *Queries) SearchIssuesByText(ctx context.Context, arg SearchIssuesByTextParams) ([]SearchIssuesByTextRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIssuesByText,
		arg.QueryText,
		arg.FilterStatus,
		arg.Status,
		arg.FilterAssignedTo,
		arg.AssignedTo,
		arg.FilterExcludeID,
		arg.ExcludeID,
		arg.FilterTags,
		pq.Array(arg.Tags),
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIssuesByTextRow
	for rows.Next() {
		var i SearchIssuesByTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.TagsJson,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Status,
			&i.ClosedAtUnixNano,
			&i.ClosedBy,
			&i.ClosedReason,
			&i.ClosedReasonNote,
			&i.TagScoresJson,
			&i.EmbeddingText,
			&i.AssignedTo,
			&i.TextScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
