// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_issues_by_embedding.sql

package issuesdb

import (
	"context"
	"encoding/json"

	"github.com/lib/pq"
)

const searchIssuesByEmbedding = `-- name: SearchIssuesByEmbedding :many
SELECT
  id,
  raw,
  tags_json,
  created_by,
  created_at_unix_nano,
  status,
  closed_at_unix_nano,
  closed_by,
  closed_reason,
  closed_reason_note,
  tag_scores_json,
  COALESCE(embedding_vector::text, '') AS embedding_text,
  assigned_to,
  (embedding_vector <=> $1::vector) AS semantic_distance
FROM issues
WHERE embedding_vector IS NOT NULL
  AND vector_dims(embedding_vector) = $2
  AND (NOT $3::bool OR status = $4::text)
  AND (NOT $5::bool OR LOWER(assigned_to) = LOWER($6::text))
  AND (NOT $7::bool OR id <> $8::text)
  AND (
    NOT $9::bool
    OR EXISTS (
      SELECT 1
      FROM jsonb_array_elements_text(tags_json) AS tag
      WHERE LOWER(tag) = ANY($10::text[])
    )
    OR EXISTS (
      SELECT 1
      FROM jsonb_to_recordset(tag_scores_json) AS score(tag text, relevance double precision)
      WHERE score.relevance >= 0.3
        AND LOWER(score.tag) = ANY($10::text[])
    )
  )
ORDER BY semantic_distance ASC, created_at_unix_nano DESC, id ASC
LIMIT $12
OFFSET $11
`

type SearchIssuesByEmbeddingParams struct {
	QueryVector      interface{}
	EmbeddingDims    interface{}
	FilterStatus     bool
	Status           string
	FilterAssignedTo bool
	AssignedTo       string
	FilterExcludeID  bool
	ExcludeID        string
	FilterTags       bool
	Tags             []string
	OffsetCount      int32
	LimitCount       int32
}

type SearchIssuesByEmbeddingRow struct {
	ID                string
	Raw               string
	TagsJson          json.RawMessage
	CreatedBy         string
	CreatedAtUnixNano int64
	Status            string
	ClosedAtUnixNano  int64
	ClosedBy          string
	ClosedReason      string
	ClosedReasonNote  string
	TagScoresJson     json.RawMessage
	EmbeddingText     interface{}
	AssignedTo        string
	SemanticDistance  interface{}
}

func (q *Queries) SearchIssuesByEmbedding(ctx context.Context, arg SearchIssuesByEmbeddingParams) ([]SearchIssuesByEmbeddingRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIssuesByEmbedding,
		arg.QueryVector,
		arg.EmbeddingDims,
		arg.FilterStatus,
		arg.Status,
		arg.FilterAssignedTo,
		arg.AssignedTo,
		arg.FilterExcludeID,
		arg.ExcludeID,
		arg.FilterTags,
		pq.Array(arg.Tags),
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIssuesByEmbeddingRow
	for rows.Next() {
		var i SearchIssuesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Raw,
			&i.TagsJson,
			&i.CreatedBy,
			&i.CreatedAtUnixNano,
			&i.Status,
			&i.ClosedAtUnixNano,
			&i.ClosedBy,
			&i.ClosedReason,
			&i.ClosedReasonNote,
			&i.TagScoresJson,
			&i.EmbeddingText,
			&i.AssignedTo,
			&i.SemanticDistance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
