// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_tag_specificity.sql

package issuesdb

import (
	"context"
	"database/sql"
)

const updateTagSpecificity = `-- name: UpdateTagSpecificity :exec
UPDATE tags SET
    specificity = $2,
    specificity_llm = $3,
    specificity_embedding = $4,
    specificity_computed_at = $5
WHERE name = $1
`

type UpdateTagSpecificityParams struct {
	Name                  string
	Specificity           sql.NullFloat64
	SpecificityLlm        sql.NullFloat64
	SpecificityEmbedding  sql.NullFloat64
	SpecificityComputedAt sql.NullTime
}

func (q *Queries) UpdateTagSpecificity(ctx context.Context, arg UpdateTagSpecificityParams) error {
	_, err := q.db.ExecContext(ctx, updateTagSpecificity,
		arg.Name,
		arg.Specificity,
		arg.SpecificityLlm,
		arg.SpecificityEmbedding,
		arg.SpecificityComputedAt,
	)
	return err
}
