// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_issue_refinement.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const updateIssueRefinement = `-- name: UpdateIssueRefinement :exec
UPDATE issues
SET raw = $1,
    tags_json = $2,
    tag_scores_json = $3,
    embedding_vector = $4::vector
WHERE id = $5
`

type UpdateIssueRefinementParams struct {
	Raw           string
	TagsJson      json.RawMessage
	TagScoresJson json.RawMessage
	Column4       interface{}
	ID            string
}

func (q *Queries) UpdateIssueRefinement(ctx context.Context, arg UpdateIssueRefinementParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueRefinement,
		arg.Raw,
		arg.TagsJson,
		arg.TagScoresJson,
		arg.Column4,
		arg.ID,
	)
	return err
}
