// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_tag.sql

package issuesdb

import (
	"context"
	"encoding/json"
)

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (name, description, created_at_unix_nano, embedding_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT(name) DO UPDATE SET
    description = CASE
        WHEN excluded.description <> '' THEN excluded.description
        ELSE tags.description
    END,
    embedding_json = CASE
        WHEN excluded.embedding_json <> '[]' THEN excluded.embedding_json
        ELSE tags.embedding_json
    END
`

type UpsertTagParams struct {
	Name              string
	Description       string
	CreatedAtUnixNano int64
	EmbeddingJson     json.RawMessage
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.Name,
		arg.Description,
		arg.CreatedAtUnixNano,
		arg.EmbeddingJson,
	)
	return err
}
