// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_tag.sql

package issuesdb

import (
	"context"
)

const upsertTag = `-- name: UpsertTag :exec
INSERT INTO tags (name, description, created_at_unix_nano, embedding_vector)
VALUES ($1, $2, $3, $4::vector)
ON CONFLICT(name) DO UPDATE SET
    description = CASE
        WHEN excluded.description <> '' THEN excluded.description
        ELSE tags.description
    END,
    embedding_vector = CASE
        WHEN excluded.embedding_vector IS NOT NULL THEN excluded.embedding_vector
        ELSE tags.embedding_vector
    END
`

type UpsertTagParams struct {
	Name              string
	Description       string
	CreatedAtUnixNano int64
	Column4           interface{}
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertTag,
		arg.Name,
		arg.Description,
		arg.CreatedAtUnixNano,
		arg.Column4,
	)
	return err
}
