ALTER TABLE issues ADD COLUMN status TEXT NOT NULL DEFAULT 'open';
ALTER TABLE issues ADD COLUMN closed_at_unix_nano INTEGER NOT NULL DEFAULT 0;
ALTER TABLE issues ADD COLUMN closed_by TEXT NOT NULL DEFAULT '';
