"use client";

import Link from "next/link";
import { useMemo } from "react";
import { LayersIcon } from "lucide-react";

import { AppShell } from "@/components/app-shell";
import { AppSidebar } from "@/components/app-sidebar";
import { IssueCard } from "@/components/issue-card";
import { SiteHeader } from "@/components/site-header";
import { TagBadge } from "@/components/tag-badge";
import { useIssues } from "@/hooks/use-issues";
import { useRegion } from "@/hooks/use-region";

type Props = {
  id: string;
};

const BUCKET_ORDER = ["<1w", "1-4w", "1-3m", "3m+"] as const;

export function ClusterRegionDetailPage({ id }: Props) {
  const { data: region, error: regionError, isLoading: regionLoading } = useRegion(
    "cluster",
    id,
  );
  const { data: allIssues = [], isLoading: issuesLoading } = useIssues("all");

  const memberIDs = useMemo(() => new Set(allIssues.map((i) => i.id)), [allIssues]);

  // The region payload doesn't ship the member ID list — we filter from the
  // full issue list using the cluster's tags as a proxy. The detail page
  // shows the same metric numbers the API returned, plus a best-effort
  // member list (issues whose top tag matches one of the cluster's labels).
  const labelTags = useMemo(() => {
    if (!region) return [] as string[];
    return region.region.label
      .split(/[+,/]/)
      .map((t) => t.trim())
      .filter(Boolean);
  }, [region]);

  const candidateIssues = useMemo(() => {
    if (!region) return [];
    return allIssues
      .filter((issue) => memberIDs.has(issue.id))
      .filter((issue) => {
        const tagScores = issue.tagScores ?? [];
        return tagScores.some(
          (score) => score.relevance >= 0.4 && labelTags.includes(score.tag),
        );
      })
      .sort((a, b) => {
        if (a.status !== b.status) return a.status === "open" ? -1 : 1;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
  }, [allIssues, memberIDs, labelTags, region]);

  const loading = regionLoading || issuesLoading;
  const notFound = !regionLoading && region != null && region.metrics.mass === 0;

  return (
    <AppShell sidebar={<AppSidebar showThingsSection={false} />}>
      <SiteHeader
        title={region?.region.label || id}
        eyebrow="Cluster region"
        subtitle="Issues that cluster together in the semantic projection."
        meta={
          region ? (
            <span className="font-mono text-[10px] text-muted-foreground">{id}</span>
          ) : undefined
        }
        actions={
          <Link
            href="/regions"
            className="rounded-md border border-border px-3 py-1 text-xs font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          >
            Back to regions
          </Link>
        }
      />

      <div className="app-scrollarea min-h-0 flex-1 overflow-y-auto">
        <div className="flex w-full flex-col gap-6 px-4 py-6 lg:px-6 xl:px-8">
          {loading && <p className="text-sm text-muted-foreground">Loading cluster…</p>}

          {regionError && (
            <div className="app-status-warning text-sm">
              Failed to load cluster: {regionError.message}
            </div>
          )}

          {notFound && (
            <div className="app-surface rounded-[1.5rem] p-5">
              <h3 className="text-sm font-semibold">Cluster not found</h3>
              <p className="mt-2 text-xs text-muted-foreground">
                Cluster IDs are derived from the cluster&apos;s member issues. When the
                cluster&apos;s members change, the ID changes too. This URL may have been
                generated by an earlier corpus snapshot.{" "}
                <Link href="/regions?kind=cluster" className="underline">
                  See the current clusters
                </Link>
                .
              </p>
            </div>
          )}

          {region && region.metrics.mass > 0 && (
            <>
              <section className="app-surface rounded-[1.5rem] p-5">
                <div className="flex items-center gap-2">
                  <LayersIcon className="size-4 text-muted-foreground" />
                  <h3 className="text-sm font-semibold">Cluster metrics</h3>
                </div>

                <div className="mt-4 grid grid-cols-3 gap-3">
                  <DetailCell label="Open" value={region.metrics.massOpen} />
                  <DetailCell label="Closed" value={region.metrics.massClosed} />
                  <DetailCell label="Mass" value={region.metrics.mass} />
                </div>

                {region.metrics.ageBuckets && region.metrics.ageBuckets.length > 0 && (
                  <div className="mt-4">
                    <p className="text-[10px] font-medium uppercase tracking-[0.12em] text-muted-foreground">
                      Open issues by age
                    </p>
                    <ol className="mt-2 space-y-1.5">
                      {BUCKET_ORDER.map((label) => {
                        const bucket = region.metrics.ageBuckets?.find(
                          (b) => b.label === label,
                        ) ?? { label, count: 0 };
                        const max = Math.max(
                          1,
                          ...(region.metrics.ageBuckets ?? []).map((b) => b.count),
                        );
                        return (
                          <li
                            key={bucket.label}
                            className="flex items-center gap-2 text-xs"
                          >
                            <span className="w-10 text-muted-foreground tabular-nums">
                              {bucket.label}
                            </span>
                            <div className="relative h-2 flex-1 rounded-full bg-border">
                              <div
                                className="absolute inset-y-0 left-0 rounded-full bg-primary/60"
                                style={{ width: `${(bucket.count / max) * 100}%` }}
                              />
                            </div>
                            <span className="w-6 text-right tabular-nums text-muted-foreground">
                              {bucket.count}
                            </span>
                          </li>
                        );
                      })}
                    </ol>
                  </div>
                )}

                <div className="mt-4 grid grid-cols-3 gap-3">
                  <FlowDetailCell
                    label={`Growth (${region.metrics.window.label})`}
                    rate={region.metrics.growth}
                  />
                  <FlowDetailCell
                    label={`Closure (${region.metrics.window.label})`}
                    rate={region.metrics.closure}
                  />
                  <FlowDetailCell
                    label={`Churn (${region.metrics.window.label})`}
                    rate={region.metrics.churn}
                  />
                </div>

                {labelTags.length > 0 && (
                  <div className="mt-4 flex flex-wrap items-center gap-2">
                    <span className="text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
                      Top tags
                    </span>
                    {labelTags.map((tag) => (
                      <TagBadge key={tag} tag={tag} />
                    ))}
                  </div>
                )}

                <p className="mt-4 text-[11px] text-muted-foreground">
                  Cluster boundaries are derived from k-means over the semantic
                  projection. The cluster ID is a hash of its members — when the
                  membership shifts, the ID changes and old URLs stop resolving.
                </p>

                <div className="mt-4">
                  <Link
                    href={`/map?cluster=${encodeURIComponent(id)}`}
                    className="inline-flex items-center gap-1 rounded-md border border-border px-3 py-1 text-xs font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                  >
                    View on map →
                  </Link>
                </div>
              </section>

              {candidateIssues.length > 0 && (
                <section className="app-surface rounded-[1.5rem] p-5">
                  <h3 className="text-sm font-semibold">Member issues</h3>
                  <p className="mt-1 text-xs text-muted-foreground">
                    Issues whose top tag matches one of the cluster&apos;s dominant tags.
                  </p>
                  <div className="mt-4 space-y-2">
                    {candidateIssues.map((issue) => (
                      <IssueCard
                        key={issue.id}
                        issue={issue}
                        href={`/issues/${issue.id}`}
                      />
                    ))}
                  </div>
                </section>
              )}
            </>
          )}
        </div>
      </div>
    </AppShell>
  );
}

function DetailCell({ label, value }: { label: string; value: number }) {
  return (
    <div className="app-subtle-surface rounded-[1.25rem] px-3 py-2.5">
      <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
        {label}
      </p>
      <p className="mt-1 text-xl font-semibold tabular-nums">{value}</p>
    </div>
  );
}

function FlowDetailCell({
  label,
  rate,
}: {
  label: string;
  rate?: { count: number; perDay: number } | null;
}) {
  return (
    <div className="app-subtle-surface rounded-[1.25rem] px-3 py-2.5">
      <p className="text-[10px] font-medium uppercase tracking-[0.14em] text-muted-foreground">
        {label}
      </p>
      {rate ? (
        <>
          <p className="mt-1 text-xl font-semibold tabular-nums">{rate.count}</p>
          <p className="text-[10px] tabular-nums text-muted-foreground">
            {rate.perDay.toFixed(2)}/day
          </p>
        </>
      ) : (
        <p className="mt-1 text-xl font-semibold tabular-nums text-muted-foreground">—</p>
      )}
    </div>
  );
}
